/**
 * Common/System Error Codes (9xx prefix)
 * 通用/系统相关错误码
 */

// Common Error Code Constants (string enum)
export const CommonErrorCode = {
  IdMustUUID: '911500',
  InnerError: '900500',
  InternalServerError: '900503',
  BadRequest: '900400',
  Unknown: '900501',
  GetStorageNull: '900404',
  DbCreateError: '900502',
  DbUpdateError: '901502',
  DbDeleteError: '902502',
  DbQueryError: '903502',
  TemplateNotFound: '904404',
  InvalidParameters: '901400',
  SignatureError: '902401',
  TooManyFolders: '903402',
  TooManyFiles: '904403',
  NotFound: '905404',
  PlanIsNotExist: '906404',
  PlanIsDeleted: '906405',
  RecommendPlanNotFound: '200',
  CreateOrderFail: '907406',
  OrderIsNotExist: '908407',
  SystemUnHealthy: '910500',
  ParameterError: '911400',

  // Third-party service errors
  GetProviderUserInfoError: '911408',
  RabbitmqQueueIsNotExist: '912409',
  StorageResponseFailed: '913510',
  BatchDeleteFolderFail: '914511',
  InitiateMultipartUploadError: '915412',
  QrcodeGenerateError: '916513',
  FileServiceUnsupportedVendor: '917414',
  QiniuZipDownloadError: '918515',
  QiniuQueryFopStatusError: '919516',
  QiniuUploaderError: '920517',
  S3NoSuchKey: '921518',
  S3NoSuchBucket: '922519',
  UnAuthorized: '923402',
  UnauthorizedByKey: '924403',
  TooFrequent: '925429',
  InvalidToken: '926404',
  InvalidEnv: '927505',
  InvalidRedis: '928506',
  TextCensorValidFailed: '928508',
  SessionExpired: '929410',

  // Feature errors
  FeatureAlreadyExists: '900403',
  FeatureNotFound: '901404',
  FeatureHasPermissions: '902404',
  SomeFeaturesHavePermissions: '903404',

  // WeChat errors
  WechatAccessTokenError: '990404',
  WechatMiniProgramQRCodeError: '990405',

  // LLM/Jina AI errors
  LLMJinaAiEmbeddingError: '999001',
  LLMJinaAiRerankError: '999002',
  LLMJinaAiReadError: '999003',
  LLMJinaAiSearchError: '999004',
  LLMJinaAiClassifyError: '999005',
  LLMJinaAiSegmentError: '999006',
  LLMJinaAiGRelatedError: '999007',
  LLMJinaAiDeepsearchError: '999008',

  // Storage errors
  S3ClientInitializationError: '999010',
  InvalidVideoUri: '999011',
  InvalidTaskId: '999012',
  MissingVendor: '999013',
} as const;

export type CommonErrorCode =
  (typeof CommonErrorCode)[keyof typeof CommonErrorCode];

// Common Error Type Keys (for i18n)
export const CommonErrorTypes: Record<CommonErrorCode, string> = {
  [CommonErrorCode.IdMustUUID]: 'idMustUUID',
  [CommonErrorCode.InnerError]: 'innerError',
  [CommonErrorCode.InternalServerError]: 'internalServerError',
  [CommonErrorCode.BadRequest]: 'badRequest',
  [CommonErrorCode.Unknown]: 'unknown',
  [CommonErrorCode.GetStorageNull]: 'getStorageNull',
  [CommonErrorCode.DbCreateError]: 'dbCreateError',
  [CommonErrorCode.DbUpdateError]: 'dbUpdateError',
  [CommonErrorCode.DbDeleteError]: 'dbDeleteError',
  [CommonErrorCode.DbQueryError]: 'dbQueryError',
  [CommonErrorCode.TemplateNotFound]: 'templateNotFound',
  [CommonErrorCode.InvalidParameters]: 'invalidParameters',
  [CommonErrorCode.SignatureError]: 'signatureError',
  [CommonErrorCode.TooManyFolders]: 'tooManyFolders',
  [CommonErrorCode.TooManyFiles]: 'tooManyFiles',
  [CommonErrorCode.NotFound]: 'notFound',
  [CommonErrorCode.PlanIsNotExist]: 'planIsNotExist',
  [CommonErrorCode.PlanIsDeleted]: 'planIsDeleted',
  [CommonErrorCode.RecommendPlanNotFound]: 'recommendPlanNotFound',
  [CommonErrorCode.CreateOrderFail]: 'createOrderFail',
  [CommonErrorCode.OrderIsNotExist]: 'orderIsNotExist',
  [CommonErrorCode.SystemUnHealthy]: 'systemUnHealthy',
  [CommonErrorCode.ParameterError]: 'parameterError',
  [CommonErrorCode.GetProviderUserInfoError]: 'getProviderUserInfoError',
  [CommonErrorCode.RabbitmqQueueIsNotExist]: 'rabbitmqQueueIsNotExist',
  [CommonErrorCode.StorageResponseFailed]: 'storageResponseFailed',
  [CommonErrorCode.BatchDeleteFolderFail]: 'batchDeleteFolderFail',
  [CommonErrorCode.InitiateMultipartUploadError]: 'initiateMultipartUploadError',
  [CommonErrorCode.QrcodeGenerateError]: 'qrcodeGenerateError',
  [CommonErrorCode.FileServiceUnsupportedVendor]: 'fileServiceUnsupportedVendor',
  [CommonErrorCode.QiniuZipDownloadError]: 'qiniuZipDownloadError',
  [CommonErrorCode.QiniuQueryFopStatusError]: 'qiniuQueryFopStatusError',
  [CommonErrorCode.QiniuUploaderError]: 'qiniuUploaderError',
  [CommonErrorCode.S3NoSuchKey]: 's3NoSuchKey',
  [CommonErrorCode.S3NoSuchBucket]: 's3NoSuchBucket',
  [CommonErrorCode.UnAuthorized]: 'unAuthorized',
  [CommonErrorCode.UnauthorizedByKey]: 'unauthorizedByKey',
  [CommonErrorCode.TooFrequent]: 'tooFrequent',
  [CommonErrorCode.InvalidToken]: 'invalidToken',
  [CommonErrorCode.InvalidEnv]: 'invalidEnv',
  [CommonErrorCode.InvalidRedis]: 'invalidRedis',
  [CommonErrorCode.TextCensorValidFailed]: 'textCensorValidFailed',
  [CommonErrorCode.SessionExpired]: 'sessionExpired',
  [CommonErrorCode.FeatureAlreadyExists]: 'featureAlreadyExists',
  [CommonErrorCode.FeatureNotFound]: 'featureNotFound',
  [CommonErrorCode.FeatureHasPermissions]: 'featureHasPermissions',
  [CommonErrorCode.SomeFeaturesHavePermissions]: 'someFeaturesHavePermissions',
  [CommonErrorCode.WechatAccessTokenError]: 'wechatAccessTokenError',
  [CommonErrorCode.WechatMiniProgramQRCodeError]: 'wechatMiniProgramQRCodeError',
  [CommonErrorCode.LLMJinaAiEmbeddingError]: 'llmJinaAiEmbeddingError',
  [CommonErrorCode.LLMJinaAiRerankError]: 'llmJinaAiRerankError',
  [CommonErrorCode.LLMJinaAiReadError]: 'llmJinaAiReadError',
  [CommonErrorCode.LLMJinaAiSearchError]: 'llmJinaAiSearchError',
  [CommonErrorCode.LLMJinaAiClassifyError]: 'llmJinaAiClassifyError',
  [CommonErrorCode.LLMJinaAiSegmentError]: 'llmJinaAiSegmentError',
  [CommonErrorCode.LLMJinaAiGRelatedError]: 'llmJinaAiGRelatedError',
  [CommonErrorCode.LLMJinaAiDeepsearchError]: 'llmJinaAiDeepsearchError',
  [CommonErrorCode.S3ClientInitializationError]: 's3ClientInitializationError',
  [CommonErrorCode.InvalidVideoUri]: 'invalidVideoUri',
  [CommonErrorCode.InvalidTaskId]: 'invalidTaskId',
  [CommonErrorCode.MissingVendor]: 'missingVendor',
};

// Common Error HTTP Status mapping
export const CommonErrorHttpStatus: Record<CommonErrorCode, number> = {
  [CommonErrorCode.IdMustUUID]: 400,
  [CommonErrorCode.InnerError]: 500,
  [CommonErrorCode.InternalServerError]: 500,
  [CommonErrorCode.BadRequest]: 200,
  [CommonErrorCode.Unknown]: 500,
  [CommonErrorCode.GetStorageNull]: 200,
  [CommonErrorCode.DbCreateError]: 200,
  [CommonErrorCode.DbUpdateError]: 500,
  [CommonErrorCode.DbDeleteError]: 500,
  [CommonErrorCode.DbQueryError]: 500,
  [CommonErrorCode.TemplateNotFound]: 200,
  [CommonErrorCode.InvalidParameters]: 200,
  [CommonErrorCode.SignatureError]: 200,
  [CommonErrorCode.TooManyFolders]: 200,
  [CommonErrorCode.TooManyFiles]: 200,
  [CommonErrorCode.NotFound]: 200,
  [CommonErrorCode.PlanIsNotExist]: 200,
  [CommonErrorCode.PlanIsDeleted]: 200,
  [CommonErrorCode.RecommendPlanNotFound]: 200,
  [CommonErrorCode.CreateOrderFail]: 200,
  [CommonErrorCode.OrderIsNotExist]: 200,
  [CommonErrorCode.SystemUnHealthy]: 200,
  [CommonErrorCode.ParameterError]: 400,
  [CommonErrorCode.GetProviderUserInfoError]: 200,
  [CommonErrorCode.RabbitmqQueueIsNotExist]: 200,
  [CommonErrorCode.StorageResponseFailed]: 200,
  [CommonErrorCode.BatchDeleteFolderFail]: 200,
  [CommonErrorCode.InitiateMultipartUploadError]: 200,
  [CommonErrorCode.QrcodeGenerateError]: 200,
  [CommonErrorCode.FileServiceUnsupportedVendor]: 200,
  [CommonErrorCode.QiniuZipDownloadError]: 200,
  [CommonErrorCode.QiniuQueryFopStatusError]: 200,
  [CommonErrorCode.QiniuUploaderError]: 200,
  [CommonErrorCode.S3NoSuchKey]: 200,
  [CommonErrorCode.S3NoSuchBucket]: 200,
  [CommonErrorCode.UnAuthorized]: 401,
  [CommonErrorCode.UnauthorizedByKey]: 401,
  [CommonErrorCode.TooFrequent]: 200,
  [CommonErrorCode.InvalidToken]: 401,
  [CommonErrorCode.InvalidEnv]: 200,
  [CommonErrorCode.InvalidRedis]: 200,
  [CommonErrorCode.TextCensorValidFailed]: 200,
  [CommonErrorCode.SessionExpired]: 410,
  [CommonErrorCode.FeatureAlreadyExists]: 409,
  [CommonErrorCode.FeatureNotFound]: 404,
  [CommonErrorCode.FeatureHasPermissions]: 403,
  [CommonErrorCode.SomeFeaturesHavePermissions]: 405,
  [CommonErrorCode.WechatAccessTokenError]: 200,
  [CommonErrorCode.WechatMiniProgramQRCodeError]: 200,
  [CommonErrorCode.LLMJinaAiEmbeddingError]: 500,
  [CommonErrorCode.LLMJinaAiRerankError]: 500,
  [CommonErrorCode.LLMJinaAiReadError]: 500,
  [CommonErrorCode.LLMJinaAiSearchError]: 500,
  [CommonErrorCode.LLMJinaAiClassifyError]: 500,
  [CommonErrorCode.LLMJinaAiSegmentError]: 500,
  [CommonErrorCode.LLMJinaAiGRelatedError]: 500,
  [CommonErrorCode.LLMJinaAiDeepsearchError]: 500,
  [CommonErrorCode.S3ClientInitializationError]: 500,
  [CommonErrorCode.InvalidVideoUri]: 400,
  [CommonErrorCode.InvalidTaskId]: 400,
  [CommonErrorCode.MissingVendor]: 400,
};
